create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists newsletter_subscribers_email_unique_idx
  on public.newsletter_subscribers (lower(email));

alter table public.newsletter_subscribers enable row level security;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'public'
      and tablename = 'newsletter_subscribers'
      and policyname = 'newsletter_public_insert'
  ) then
    create policy newsletter_public_insert
      on public.newsletter_subscribers
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

notify pgrst, 'reload schema';

grant usage on schema public to anon, authenticated;
grant insert on table public.newsletter_subscribers to anon, authenticated;

do $$
begin
  if exists (
    select 1
    from pg_class c
    join pg_namespace n on n.oid = c.relnamespace
    where n.nspname = 'public'
      and c.relname = 'newsletter_subscribers_id_seq'
      and c.relkind = 'S'
  ) then
    grant usage, select on sequence public.newsletter_subscribers_id_seq to anon, authenticated;
  end if;
end
$$;
