create table if not exists public.newsletter_subscribers (
  id bigint generated by default as identity primary key,
  email text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists newsletter_subscribers_email_unique_idx
  on public.newsletter_subscribers (lower(email));

alter table public.newsletter_subscribers enable row level security;
